### ISSUE TITLE
Feature request: Opening .zip-files and uploading the contained .pdfs

### ISSUE THREAD

**Issue by saschafoerster** [gruessung/send2lex#3]
Some companies send their bills as .zip with a PDF and the signature. It would be nice, if the contained PDF would also be automatically uploaded to LexOffice.

**Comment by gruessung** [comment]
I'm a bit confused that GitHub didn't send me any notification about your opened issue ...
Your feature request sounds good.

So you want to extract the zip file and upload contained pdf files, right?

**Comment by saschafoerster** [comment]
Exactly! :) Some companies keep sending a .zip file with a PDF and the signature of this PDF. So it would be nice, that also these PDFs are added to LexOffice without manual work. :)

**Comment by gruessung** [comment]
Done.
