### ISSUE TITLE
PHP 7.3 End-of-life (EOL)

### ISSUE THREAD

**Issue by holzhannes** [gruessung/send2lex#5]
As far as I see it correctly, the preferred version is PHP 7.3, which no longer receives security updates. Could the whole thing be changed directly to PHP 8.0 or 8.1?

**Comment by gruessung** [comment]
I'll try it.

**Comment by gruessung** [comment]
Done. You can also use ```ghcr.io/gruessung/send2lex:main``` for your deployment now.
